project:
  type: website
  output-dir: docs

website:
  title: "Group 38's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd
      

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



